name = "problem"
version = "1.1.0"

description = "Error handling for Gleam applications"
licences = ["MIT"]
repository = { type = "github", user = "sporto", repo = "gleam-problem" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
